lexik_jwt_authentication:
    secret_key: '%jwt_secret_key%'
    encoder:
        signature_algorithm: HS256
    token_extractors:
        query_parameter:
            enabled: true
            name:    token
